name: vgv_coffee_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.4.0
  dartz: ^0.10.1
  shared_preferences: ^2.2.3
  rxdart: ^0.27.7
  cached_network_image: ^3.3.1
  path_provider: ^2.1.3
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  